### ISSUE TITLE
Concurrent requests are handled incorrectly

### ISSUE THREAD

**Issue by vytas7** [aprilahijriyan/falca#7]
Consider the following app:
```python
import asyncio
import logging

from falca.app import ASGI
from falca.resource import Resource

logging.basicConfig(level=logging.INFO)


class Sleepy(Resource):
    async def on_get(self):
        await asyncio.sleep(5)

        try:
            resp = {'test': self.request.get_param('test')}
            logging.info(resp)
            self.json(resp)
        except Exception as ex:
            logging.exception('oops')


app = ASGI(__name__)

app.add_route('/sleepy', Sleepy())
```

Running just one request at a time, it works fine.

However, issuing multiple requests in parallel, while the first one is processing, makes them return no content (?), except the last one. This is probably due to `Resource.request` and `Resource.response` being intermixed and overwritten in middleware concurrently.

```
GET /sleepy?test=2 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: 127.0.0.1:8000
User-Agent: HTTPie/1.0.3



HTTP/1.1 200 OK
content-length: 0
content-type: application/json
date: Fri, 14 May 2021 14:42:03 GMT
server: uvicorn
```

```
GET /sleepy?test=3 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: 127.0.0.1:8000
User-Agent: HTTPie/1.0.3



HTTP/1.1 200 OK
content-length: 13
content-type: application/json
date: Fri, 14 May 2021 14:42:06 GMT
server: uvicorn

{
    "test": "3"
}
```

**Comment by aprilahijriyan** [comment]
Thank you so much for investigating this bug!

After seeing this issue and confirming it. I am thinking of refactoring Requests and Responses.

The best ideas I have in mind:

* I will put a Request and Response object based on typed hints (handled by `falca.actions.flavor`)
* And also add a return-response style like [starlette](https://www.starlette.io/responses/). (This is also handled by `falca.actions.flavor`)

@vytas7 What do you think ?

**Comment by vytas7** [comment]
Heh, it's your framework, so you get to pick your adventure :smiling_imp:

> * I will put a Request and Response object based on typed hints

If you're going to take on FastAPI, I think that kind of injection is a good idea. I think [Hug](https://github.com/hugapi/hug) does something very similar.

**Comment by aprilahijriyan** [comment]
ROTFL :laughing:

**Comment by aprilahijriyan** [comment]
Hi @vytas7, I just updated. Can you test it again in the `develop` branch? for me this has been better than before.
